---
- name: clean up all
  hosts: all
  vars:
    pkg: ['httpd', 'vsftpd']
    
  tasks:
  - name: remove services
    apt:
      name: "{{ item }}"
      state: absent
    with_items:
      - httpd
      - vsftpd

#  - name: remove services
#    apt:
#      name: "{{ pkg }}"
#      state: absent

  - name: remove files
    file:
      path: "{{ item }}"
      state: absent
    with_items:
      - /etc/ansible/facts.d
      - /var/www/html/index.html
      - /var/ftp/pub/README
      - /etc/motd
