---
- name: create users
  hosts: localhost 
  connection: local

  vars:
    myusers:
      - linda
      - anna
    mygroups:
      - students
      - profs
    
  tasks:
  - name: create groups
    group:
      name: "{{ item }}"
      state: present
    with_items: "{{ mygroups }}"

  - name: create users with group membership 
    user:
      name: “{{ item[0] }}”
      state: present
      groups: "{{ mygroups }}" 
    with_nested:
      - "{{ myusers }}"
      - "{{ mygroups }}"
