---
- name: copy new index.html
  hosts: all
  tasks:
    - name: install nginx
      apt: name=nginx
#  tasks:
    - name: copy index.html
      copy:
        src: /tmp/index.html
        dest: /var/www/html/index.html
      notify:
        - restart_web
  handlers:
    - name: restart_web
      service:
        name: nginx
        state: restarted
