---
- name: copy new index.html
  hosts: all
  #force_handlers: yes
  tasks:
    - name: install nginx
      apt: name=nginx
    - name: copy index.html
      copy:
        src: /tmp/index.html
        dest: /var/www/html/index.html
      notify:
        - restart_web
    - name: copy nothing
      copy:
        src: /tmp/nothing
        dest: /nowhere
  handlers:
    - name: restart_web
      service:
        name: nginx
        state: restarted
