---
- name: check URL
  hosts: ansible2.example.com
  tasks:
    - uri:
        url: http://ubuntu.com
	return_content: yes
      register: webpage

    - name: Fail if ubuntu is not in the page content
      fail:
        msg: 'not' the right content'
      when: "ubuntu not in webpage.content"
