---
- name: check URL
  hosts: node2.ansible.local
  tasks:
    - uri:
        url: http://ubuntu.com
        return_content: yes
      register: webpage

    - name: Fail if ubuntu is not in the page content
      fail:
        msg: 'not the right content'
      when: '"ubun)))tu" not in webpage.content'
