---
- hosts: node1.ansible.local

  tasks:
    - name: configure fqdn and hostname 
      import_role:
        name: holms.fqdn
      vars:
        hostname: "my-new-hostname"
        fqdn: "{{ inventory_hostname }}"

#    - name: deploy ftp service "{{ ansible_host }}"
#      import_role:
#        name: ftp

#    - name: deploy nginx and configure virtual host
#      import_role:
#        name: nginx
#      vars:
#        virtual_host: "{{ inventory_hostname }}"

