Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"
  config.vm.hostname = "test.example.com"

  config.vm.network "private_network", ip: '192.168.100.100'
#  config.vm.network "forwarded_port", guest: 80 , host: 8080

  config.vm.provision "ansible" do |ansible|
    ansible.playbook = 'playbook.yml'
  end

  if Vagrant.has_plugin?("vagrant-vbguest")
    config.vbguest.auto_update = false
  end
end
