---
- name: update hosts (( apt.yml, line 2 ))
  hosts: all
  tasks:
  - name: Run the equivalent of "apt-get update" as a separate step (( apt.yml, line:6 ))
    apt:
      update_cache: yes

#  - name: Upgrade all packages to the latest version
#    apt:
#      name: "*"
#      state: latest
#      force_apt_get: True

  - name: install package "htop"
    apt:
      name: htop
